```{r}

install.packages("caret")
install.packages("rpart")
install.packages("rpart.plot")
install.packages("rattle")

library(tidymodels)
library(tidyverse)
library(tidymodels)
library(caret)
library(rpart)
library(rpart.plot)
library(rattle)
library(RColorBrewer)

heart <- read.csv("heart_disease-1.csv")


set.seed(12345)

split <- initial_split(
  heart,
  prop = 0.70,
  strata = HeartDisease
)

train <- training(split)
test  <- testing(split)

nrow(train)
```

```{r}
heart <- heart %>%
  mutate(
    sex = factor(Sex),
    ChestPainType = factor(ChestPainType),
    RestingECG = factor(RestingECG),
    ExerciseAngina = factor(ExerciseAngina),
    ST_Slope = factor(ST_Slope),
    HeartDisease = factor(HeartDisease,
                          levels = c(0, 1),
                          labels = c("No", "Yes"))
  )

```

```{r}
set.seed(12345)

heart_split <- initial_split(
  heart,
  prop = 0.70,
  strata = HeartDisease
)

heart_train <- training(heart_split)
heart_test <- testing(heart_split)
```

```{r}
tree1 <- rpart(
  HeartDisease ~ .,
  data = heart_train,
  method = "class"
)

fancyRpartPlot(tree1)
```
```{r}
printcp(tree1)
```
```{r}
tree1$cptable
```
```{r}
tree1$cptable[which.min(tree1$cptable[, "xerror"]), "CP"]
```
```{r}
round(tree1$cptable[which.min(tree1$cptable[, "xerror"]), "CP"], 2)
```
```{r}
tree_spec <- decision_tree(
  cost_complexity = tune()
) %>%
  set_engine("rpart") %>%
  set_mode("classification")

tree_recipe <- recipe(HeartDisease ~ ., data = heart_train)

tree_workflow <- workflow() %>%
  add_recipe(tree_recipe) %>%
  add_model(tree_spec)

set.seed(123)

heart_folds <- vfold_cv(
  heart_train,
  v = 5,
  strata = HeartDisease
)

tree_grid <- grid_regular(
  cost_complexity(),
  levels = 25
)

tree_results <- tune_grid(
  tree_workflow,
  resamples = heart_folds,
  grid = tree_grid,
  metrics = metric_set(accuracy, roc_auc)
)

collect_metrics(tree_results)
```
```{r}
autoplot(tree_results)
```

```{r}
best_acc <- select_best(tree_results, metric = "accuracy")
best_acc
```
```{r}
round(best_acc$cost_complexity, 4)
```

```{r}
final_tree_workflow <- finalize_workflow(
  tree_workflow,
  best_acc
)

final_tree_fit <- fit(
  final_tree_workflow,
  data = heart_train
)

final_tree_fit
```
```{r}
final_tree_fit %>%
  extract_fit_engine() %>%
  fancyRpartPlot()
```
```{r}
train_predictions <- predict(final_tree_fit, heart_train) %>%
  bind_cols(heart_train)

accuracy(
  train_predictions,
  truth = HeartDisease,
  estimate = .pred_class
)

```

```{r}
sens(
  train_predictions,
  truth = HeartDisease,
  estimate = .pred_class,
  event_level = "second"
)
```
```{r}
heart_train %>%
  count(HeartDisease) %>%
  mutate(prop = n / sum(n))

```
```{r}
test_predictions <- predict(final_tree_fit, heart_test) %>%
  bind_cols(heart_test)

accuracy(
  test_predictions,
  truth = HeartDisease,
  estimate = .pred_class
)

```
```{r}
test_predictions <- predict(final_tree_fit, heart_test) %>%
  bind_cols(heart_test)

accuracy(
  test_predictions,
  truth = HeartDisease,
  estimate = .pred_class
)
```

